import type { Metadata } from 'next'
import './globals.css'
import { poppins } from './assets/fonts'

export const metadata: Metadata = {
	title: 'Template Next Js',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='pt-BR'>
			<body className={`${poppins.className} antialiased`}>
				{children}
			</body>
		</html>
	)
}
